import random
from getpass import getpass
## 
llista_paraules = ["la", "i", "el", "a", "en", "que", "va", "del", "per", "les",
                   "els", "un", "amb", "es", "al", "una", "es", "com", "dels", "mes", "ser",
                  "seu", "van", "o", "no", "seva", "fou", "entre", "tambe", "pero", "als",
                   "despres", "ha", "aquest", "fins", "any", "son", "hi", "pel", "aquesta", 
                   "durant", "on", "era", "part", "altres", "anys", "gran", "ciutat", "cap", 
                   "des", "seus", "tot", "estat", "qual", "segle", "sobre", "quan", "guerra", 
                   "ja", "havia", "molt", "rei", "dos", "primer", "nom", "fer", "se", "aixi", 
                   "li", "sant", "encara", "pels", "primera", "seves", "contra", "te", "partit", 
                   "esta", "mateix", "forma", "aC", "pot", "nord", "tres", "temps", "fill", 
                   "han", "nomes", "dues", "si", "sota", "general", "lloc", "aixo", "Barcelona", 
                   "alguns", "govern", "poder", "uns", "aquests", "mort", "nou", "sud", "tots", 
                   "fet", "sense", "França", "grup", "tant", "terme", "fa", "tenir", "segons", 
                   "mon", "regne", "exercit", "segona", "abans", "mentre", "quals", "aquestes", 
                   "familia", "Catalunya", "pais", "eren", "poden", "diferents", "nova", "molts",
                   "esglesia", "major", "club", "manera", "estats", "seua", "diversos", "grans", 
                   "que", "arribar", "troba", "poblacio", "sistema", "poble", "foren", "m", 
                   "epoca", "haver", "cada", "eleccions", "diverses", "obra", "partir", "tipus", 
                   "riu", "vida", "dia", "quatre", "poc", "regio", "exemple", "batalla", "altre", 
                   "Espanya", "Joan", "actualment", "tenen", "dins", "llavors", "centre", "algunes",
                   "important", "altra", "terra", "antic", "tenia", "zona", "obres", "estava", 
                   "pare", "III", "qui", "ara", "havien", "començar", "historia", "morir",
                   "nacional", "final", "música", "majoria", "Europa", "posteriorment", "alemanya",
                    "principal", "finalment", "passar", "punt", "territori", "illa", "unio", 
                    "imperi", "donar", "mundial", "república", "periode", "linia", "tard", 
                    "temporada", "totes", "sent", "ell", "president", "Maria", "perque", 
                    "emperador", "divisio", "politica", "equip", "mar", "castell", "universitat", 
                    "nomenat", "capital", "dir", "segon", "cosa", "aconseguir", "the", "Carles",
                    "actual", "cas", "banda", "futbol", "moment", "Roma", "santa", "provincia", 
                    "origen", "aigua", "vegada", "anomenat", "rebre", "jocs", "primers", "casa", 
                    "km", "be", "units", "paisos", "causa", "germa", "tota", "tornar", "conegut", 
                    "situada", "unes", "estan", "juliol", "metres", "frances", "Pere", "Valencia", 
                    "sol", "tal", "camp", "formar", "obtenir", "creu", "vegades", "nombre", "força",
                    "ho", "dies", "llengua", "davant", "mateixa", "prop", "moviment", "campionat", 
                    "octubre", "serra", "comte", "sovint", "carrec", "cos", "costat", "reial", 
                    "agost", "llarg", "filla", "suport", "forces", "municipi", "maig", "total", 
                    "moltes", "especialment", "civil", "popular", "ells", "juny", "comarca",
                    "importants", "tropes", "Italia", "avui", "or", "central", "titol", "estil",
                    "edat", "abril", "setembre", "cop", "corona", "anar", "situat", "resta",
                    "traves", "oest", "catala", "Arago", "espanyola", "principals", "militar",
                    "estar", "membre", "cal", "ciutats", "est", "aquell", "Madrid", "mare", 
                    "juntament", "Paris", "menys", "v", "següent", "internacional", "IV", 
                    "construccio", "s", "trobar", "gener", "pas", "pau", "exit", "francesa", 
                    "vall", "etc", "sempre", "Lluis", "especies", "obstant", "ordre", "conjunt", 
                    "grups", "ús", "membres", "mitjançant", "alt", "antiga", "vila", "habitants", 
                    "neixer", "canvi", "participar", "illes", "cinc", "XIX", "lliga", "veure", 
                    "març", "estudis", "serie", "desembre", "base", "anomenada", "fills", 
                    "malgrat", "duc", "novembre", "art", "persones", "sobretot", "ben", 
                    "tractat", "front", "crear", "elements", "troben", "alta", "premi", "escola", "sino", "espanyol", "victoria", "palau", "costa", "guanyar", "acabar", 
                    "millor", "Jaume", "tanmateix", "finals", "alemany", "homes", 
                    "principalment", "febrer", "catalana", "terres", "ni", "consell", "segles", 
                    "deu", "color", "tan", "c", "partits", "copa", "coneguda", "Josep", "format", 
                    "interior", "establir", "nivell", "desenvolupament", "Felip", "paper", 
                    "gairebe", "vers", "oficial", "princep", "voltant", "posicio", "Castella", 
                    "treball", "aleshores", "deixar", "municipal", "proces", "direccio", "petit", 
                    "dret", "ocupar", "ministre", "teoria", "primeres", "construir", "gracies", 
                    "mitjana", "qualsevol", "superior", "occidental", "estudiar", "servir", 
                    "únic", "seria", "cultura", "olimpics", "angles", "escut", "influencia", 
                    "of", "romans", "monestir", "carrera", "esquerra", "apareix", "mantenir", 
                    "oriental", "propi", "comtat", "director", "superficie", "genere", "XX", 
                    "sis", "jove", "mans", "probablement", "produccio", "districte", "milions", 
                    "x", "Jordi", "grec", "Anglaterra", "pla", "diu", "servei", "formacio", 
                    "energia", "entrar", "via", "llum", "estiu", "espai", "prendre", "Alfons", 
                    "estructura", "relacio", "mai", "activitat", "teatre", "massa", "San", 
                    "quedar", "port", "roma", "social", "Enric", "natural", "situacio", 
                    "convertir", "creacio", "parlament", "funcio", "papa", "defensa", 
                    "revolucio", "societat", "territoris", "plaça", "mesos", "decada", "edifici", 
                    "restes", "America", "control", "generals", "llibre", "categoria", "pobles", 
                    "seleccio", "dona", "tracta", "mes", "llei", "unit", "porta", "departament", 
                    "museu", "bisbe", "conca", "fan", "barranc", "escriure", "pont", "animals", 
                    "possible", "parts", "zones", "principis", "reina", "estacio", "Francesc", 
                    "independencia", "planta", "Ramon", "única", "muntanya", "orde", "aviat", 
                    "real", "especie", "presencia", "produir", "realitzar", "torre", "africa", 
                    "tercer", "XVIII", "romana", "punts", "politic", "quantitat", "sembla", 
                    "reis", "resultat", "y", "deu", "domini", "esdevenir", "estudi", "lluita", 
                    "temple", "meitat", "últim", "acord", "menor", "Rússia", "generalment", 
                    "proves", "drets", "versio", "font", "set", "degut", "enviar", "portar", 
                    "importancia", "llocs", "tron", "nous", "seguir", "treballar", "b", "area", 
                    "catedral", "model", "comandament", "petita", "Portugal", "normalment", 
                    "estaven", "perdre", "XIII", "cursa", "f", "organitzacio", "seues", 
                    "alemanys", "tercera", "decidir", "ella", "jugar", "classe", "propia", 
                    "dinastia", "canto", "Egipte", "sovietica", "companyia", "valencia", 
                    "projecte", "viure", "antics", "musical", "XVI", "nucli", "atac", "noves", 
                    "home", "sistemes", "comunitat", "tradicio", "maxima", "Ferran", "l", 
                    "socialista", "unitat", "baixa", "Guillem", "escollit", "ambdos", "austria", 
                    "local", "baix", "municipis", "conte", "llati", "caracter", "tenien", 
                    "carrer", "Grecia", "inclou", "representacio", "formen", "bona", 
                    "governador", "VI", "son", "catalans", "data", "llengües", "comandant", 
                    "marc", "disc", "flota", "lliure", "congres", "mesura", "presenta", "barri", 
                    "britanic", "Londres", "igual", "passa", "fi", "accio", "diferencia", 
                    "permetre", "e", "joc", "regions", "comença", "campanya", "junt", "Mexic", 
                    "dona", "provincies", "utilitza", "aquells", "petits", "competicio", 
                    "anterior", "permet", "princesa", "europea", "blanc", "principi", "cort", 
                    "formes", "continuar", "armes", "diputat", "honor", "matrimoni", "elles", 
                    "original", "objectiu", "francesos", "posar", "sigui", "problemes", "vots", 
                    "aproximadament", "economia", "Mallorca", "regim", "Antoni", "capella", 
                    "Bretanya", "dreta", "fundar", "Generalitat", "frontera", "funcions", "Xina", 
                    "iniciar", "fora", "utilitzar", "peninsula", "nombrosos", "conquesta", 
                    "York", "Alexandre", "casos", "independent", "tradicional", "relacions", 
                    "soldats", "podia", "temporades", "mestre", "XIV", "considerat", "nacionals", 
                    "podria", "pel·licula", "etapa", "opera", "destacar", "professor", "senyor", 
                    "casar", "públic", "dirigir", "plantes", "programa", "formula", 
                    "constitucio", "regnat", "asia", "linies", "capacitat", "caracteristiques", 
                    "dur", "desenvolupar", "tingue", "n", "aire", "ajuntament", "doncs", "Jose", 
                    "comunista", "parc", "aliats", "edicio", "aliança", "darrer", "militars", 
                    "coalicio", "considera", "favor", "lleo", "cami", "dones", "XII", "arribada", 
                    "mitja", "pedra", "europeu", "valor", "petites", "mig", "sols", "velocitat", 
                    "objectes", "fos", "resistencia", "XVII", "aigües", "següents", "muntanyes", 
                    "volta", "equips", "Miquel", "revolta", "autor", "material", "paraula", 
                    "sentit", "debutar", "italia", "just", "nombroses", "especial", "XV", "fent", 
                    "hauria", "informacio", "coneix", "entrada", "aconsegui", "canal", "corts", 
                    "camps", "cultural", "fons", "revista", "abandonar", "estrelles", 
                    "indústria", "feia", "intentar", "atacar", "donat", "pocs", "existencia", 
                    "Pallars", "academia", "alhora", "arriba", "colonia", "composicio", "rep", 
                    "Atenes", "Manuel", "imatge", "Sicilia", "sector", "institut", "evitar", 
                    "efecte", "economica", "esposa", "extrem", "sera", "medalla", "invasio", 
                    "conseqüencia", "dades", "prova", "treballs", "última", "fundacio", "Girona", 
                    "veu", "bandera", "formada", "vuit", "aqui", "comú", "FC", "cases", "VII", 
                    "llista", "operacio", "Japo", "figura", "mercat", "presentar", "darrera", 
                    "derrotar", "los", "termes", "arab", "inici", "assassinat", "fort", 
                    "comença", "comissio", "ajuda", "distancia", "rus", "element", "persona", 
                    "setge", "grecs", "rius", "condicions", "baixos", "passa", "anomena", "gent", 
                    "personatges", "coneguts", "corrent", "comerç", "vaixells", "demanar", 
                    "recuperar", "idea", "hivern", "moderna", "futur", "circuit", "secretari", 
                    "creat", "noms", "oposicio", "romandre", "potser", "ocasions", "realitat", 
                    "and", "vol", "germana", "serveis", "germans", "arquitectura", "objecte", 
                    "temes", "inicialment", "cel·lules", "interes", "fugir", "quimica", "india", 
                    "temperatura", "John", "estadi", "edificis", "ma", "motiu", "cor", 
                    "existeixen", "britanics", "expedicio", "Navarra", "pertany", "senat", 
                    "limit", "d", "fets", "succeir", "Juan", "vista", "anomenats", 
                    "administracio", "David", "destaca", "llibres", "similar", "fisica", "negre", 
                    "fusta", "grau", "destaquen", "materials", "millors", "sudest", 
                    "literatura", "parla", "representa", "actualitat", "estrella", "passat", 
                    "arc", "llibertat", "orquestra", "publicar", "mostra", "derrota", 
                    "propietat", "quant", "assolir", "diferent", "productes", "varen", "canviar", 
                    "mitjans", "activitats", "bon", "Urgell", "algun", "politics", "fonts", 
                    "viu", "XI", "grega", "rapidament", "classificacio", "ens", "jugador", 
                    "peces", "utilitzat", "exterior", "ibn", "respecte", "instruments", 
                    "Macedonia", "simbol", "trobat", "imperial", "alli", "unir", "tema", "p", 
                    "esser", "federacio", "longitud", "marina", "Berlin", "planeta", "sortir", 
                    "concepte", "significa", "carretera", "posterior", "coneixer", "locals", 
                    "mil", "prove", "von", "creixement", "disseny", "xarxa", "propietats", 
                    "aquella", "cançons", "trobava", "alçada", "guerres", "personal", "colors", 
                    "humans", "jugadors", "exercits", "italiana", "unitats", "castella", 
                    "pintura", "blanca", "conflicte", "particular", "existeix", "forta", 
                    "inferior", "oficials", "derrotat", "essent", "Bernat", "industrial", 
                    "formant", "in", "fulles", "seguint", "maxim", "nau", "plata", "t", 
                    "cristians", "agricultura", "autors", "fundat", "quasi", "aparicio", "atacs", 
                    "enviat", "provocar", "assemblea", "ocupacio", "televisio", "Saint", 
                    "empresa", "contacte", "ducat", "qualitat", "directament", "joves", 
                    "utilitzen", "families", "Marti", "endavant", "produeix", "disputar", 
                    "federal", "Isabel", "caure", "mida", "caiguda", "pressio", "apareixen", 
                    "incloent", "jueus", "ajut", "apareixer", "canvis", "espanyoles", "plana", 
                    "arabs", "h", "practica", "cm", "Hitler", "llac", "retirar", "ferro", 
                    "limita", "administrativa", "sap", "podien", "segueix", "successor", "clima", 
                    "amic", "tecnica", "politiques", "evolucio", "últims", "argent", "bronze", 
                    "combat", "extensio", "varietat", "participa", "resultats", "alla", 
                    "conserva", "llarga", "casa", "ordres", "passant", "VIII", "fundada", 
                    "successio", "alguna", "comercial", "k", "aconseguint", "lluitar", "mena", 
                    "metode", "musulmans", "so", "diari", "escons", "marca", "guanya", 
                    "problema", "conquerir", "present", "Robert", "text", "moviments", 
                    "posteriors", "principat", "tribus", "antigues", "construit", "lleis", 
                    "religio", "associacio", "car", "Israel", "argentina", "filosofia", 
                    "anteriors", "canço", "localitat", "sala", "foc", "le", "trobem", "educacio", 
                    "socials", "hom", "mur", "ajudar", "diputats", "g", "Lleida", "classes", 
                    "professional", "Tarragona", "Cesar", "inclouen", "seccio", "las", "terreny", 
                    "fortalesa", "ocupada", "r", "escala", "esdevingue", "esglesies", "torna", 
                    "torna", "cert", "figures", "hereu", "totalment", "capita", "Napols", 
                    "certa", "novament", "participacio", "coll", "consol", "doble", "economic", 
                    "idees", "elevacio", "moments", "quilometres", "solar", "seguretat", 
                    "Frederic", "sudoest", "vell", "traslladar", "viatge", "personatge", 
                    "acceptar", "compta", "elegit", "huma", "mori", "Polonia", "inicia", 
                    "Belgica", "espanyols", "reforma", "artistes", "participaren", "Brasil", 
                    "lider", "residencia", "poblacions", "nordoest", "carta", "codi", 
                    "completament", "habitual", "nit", "considerar", "dominis", "historic", 
                    "Tremp", "Viena", "paraules", "nordest", "flors", "lluna", "Francisco", 
                    "operacions", "titols", "escrit", "naturals", "mediterrania", "nascut", 
                    "actuals", "basc", "europeus", "vora", "proteccio", "populars", "album", 
                    "acces", "descobrir", "mediterrani", "autonomia", "curs", "festa", "ocea", 
                    "branca", "arriba", "Jesús", "efectes", "comuna", "nacions", "serrat", 
                    "pública", "curses", "catolica", "darrers", "medicina", "tasca", "orient", 
                    "habitualment", "lletres", "queda", "crisi", "tecniques", "excepte", 
                    "ciencia", "començament", "Antonio", "clau", "medieval", "intent", "Jean", 
                    "famos", "gols", "llevant", "particules", "propis", "bosc", "exemples", 
                    "fase", "Siria", "semblant", "arquitecte", "ciencies", "presenten", 
                    "cristiana", "monarquia", "caps", "pel·licules", "August", "gotic", "pes", 
                    "coneixement", "senyal", "Harry", "roig", "Mila", "cossos", "feu", "arees", 
                    "altitud", "dirigit", "nobles", "arts", "creada", "generes", "malaltia", 
                    "musicals", "Savoia", "aplicacio", "boscos", "comites", "piano", "rao", 
                    "britanica", "liberal", "IX", "Australia", "municipals", "cinema", "matar", 
                    "ruta", "alcalde", "autoritat", "candidat", "definitivament", "escriptura", 
                    "relativament", "torneig", "ambdues", "campio", "dintre", "tingut", 
                    "compositor", "transport", "cent", "compost", "di", "comite", "gules", 
                    "materia", "blau", "declarar", "façana", "Jerusalem", "dedicada", "imatges", 
                    "torres", "recerca", "retorn", "valls", "signar", "aspecte", "col·leccio", 
                    "Jussa", "expansio", "rang", "celebrar", "hague", "quart", "Tolosa", 
                    "seguit", "dirigida", "Hongria", "masculina", "novel·la", "rock", "Tour", 
                    "prou", "eix", "hores", "infanteria", "moneda", "presidencia", "classica", 
                    "punta", "colonies", "mica", "producte", "volia", "tradicionalment", 
                    "oficialment", "PSOE", "representant", "mm", "consta", "marxar", 
                    "reconeixement", "GP", "nomenar", "incloent", "comtes", "patir", 
                    "llenguatge", "mateixos", "vegeu", "dificil", "modern", "comunitats", 
                    "atmosfera", "carrecs", "dona", "gas", "número", "ve", "Anna", "entorn", 
                    "instrument", "patrimoni", "practicament", "altura", "comarques", "exercir", 
                    "proclamar", "arribant", "Berenguer", "continua", "justicia", "roca", 
                    "anomenades", "bastant", "motor", "Napoleo", "retornar", "columnes", 
                    "naixement", "esmenta", "Constantinoble", "pintures", "podem", "Maria", 
                    "simplement", "consisteix", "Armenia", "possibilitat", "solen", 
                    "tradicionals", "infant", "net", "recursos", "sang", "valenciana", "arbres", 
                    "considerada", "estructures", "forma", "respectivament", "baixes"]
                    # "diametre", "lliures", "perses", "russa", "ambit", "exili", "feu", "fundador", "hospital", "simple", "igualment", "naus", "naval", "deixant", "regnes", "reconeixer", "denominacio", "J", "distribucio", "ciutadans", "damunt", "freqüencia", "veins", "adoptar", "publicat", "radio", "caracteristica", "feien", "reaccio", "sortida", "Moscou", "perdua", "situa", "conegudes", "versions", "comunes", "presa", "antigament", "religiosa", "humana", "nacionalista", "comunicacio", "junta", "Atlantic", "exposicio", "Suissa", ""l, "clubs", "memoria", "senyors", "valors", "animal", "article", "cara", "estatut", ""ls, "festes", "Crist", "diners", "materna", "salut", "universal", "altes", "districtes", "portes", "meridional", "possessio", "tribu", "esmentat", "peix", "historica", "cim", "defensar", "models", "ocupa", "carrers", "olimpic", "mamifers", "capaç", "pares", "pintor", "republica", "si", "cadena", "Florencia", "molta", "urba", "anell", "basat", "bizanti", "continent", "retirada", "acaba", "anteriorment", "decisio", "immediatament", "organismes", "posicions", "Sevilla", "turo", "aplicacions", "carboni", "dit", "gaire", "potencia", "compren", "constant", "esport", "noblesa", "processos", "accions", "anomenar", "concentracio", "majors", "parroquia", "primavera", "ambient", "concert", "correspon", "arcs", "khan", "neix", "disputant", "ministeri", "ocells", "Roger", "converti", "inicial", "motius", "nombres", "preso", "conseller", "parella", "festival", "Irlanda", "visio", "treballadors", "golf", "oberta", "inicis", "matematiques", "mont", "rebe", "sola", "Suecia", "viuen", "cientifics", "conserven", "permeten", "Luis", "rebut", "components", "obrir", "basada", "llegenda", "lo", "peixos", "vint", "critica", "metodes", "organitzar", "equivalent", "interpretacio", "notable", "peu", "responsable", "concejo", "paterna", "William", "afegir", "mariscal", "negra", "ponent", "cavallers", "resposta", "representants", "descobert", "pagar", "regional", "carrega", "contingut", "italians", "avinguda", "despres", "entitat", "Granada", "poeta", "Royal", "similars", "clar", "guardia", "Venecia", "victories", "absis", "dimensions", "necessitat", "radiacio", "arribat", "Canada", "gira", "introduir", "vermell", "col·laboracio", "donen", "menors", "molecules", "vent", "catalanes", "conservar", "eleccio", "morts", "compte", "governar", "James", "reconegut", "Charles", "dedicat", "EUA", "feta", "representar", "europees", "expressio", "bases", "descobriment", "finalitzar", "magnitud", "orbita", "renaixement", "demostrar", "directe", "fe", "articles", "Baviera", "concerts", "culte", "George", "investigacio", "missio", "anglesa", "envair", "institucions", "Noguera", "torn", "u", "centres", "Franco", "reunir", "romanica", "desenvolupat", "Paul", "recentment", "aconsegueix", "internacionals", "persa", "utilitzada", "bandes", "coberta", "republicana", "restauracio", "anava", "autoritats", "democracia", "pell", "propies", "concili", "dalt", "diferencies", "fusio", "Pompeu", "proper", "hora", "originalment", "Pedro", "realitza", "Santiago", "compondre", "disputa", "legislatives", "utilitzant", "carn", "construida", "donant", "electrons", "exits", "ADN", "deriva", "representen", "col·legi", "historia", "tram", "almenys", "descendents", "franceses", "estandard", "mesures", "amor", "complex", "femenina", "presoner", "mitologia", "patro", "castells", "escena", "manca", "Alacant", "empreses", "programes", "almirall", "america", "analisi", "consideren", "Pacific", "tractament", "hidrogen", "voler", "da", "destacat", "res", "tocar", "vaixell", "vescomte", "experiencia", "jardi", "premis", "aspectes", "ferrocarril", "naturalesa", "nuclis", "observar", "poques", "acid", "Balears", "esdeveniments", "mante", "proteines", "Stalin", "usar", "monedes", "sectors", "terrestre", "tinent", "ample", "testament", "aliat", "celebrats", "Escocia", "limits", "oli", "ous", "actuacio", "ascens", "Astúries", "formava", "pilots", "verd", "clara", "creixer", "contrari", "malalties", "mestres", "nordamerica", "plena", "vessant", "acaba", "combatre", "densitat", "durar", "explica", "fruit", "religios", "segurament", "Borbo", "estudia", "podrien", "Albert", "certs", "condicio", "dictadura", "enemic", "timbre", "catolics", "cristianisme", "estendre", "unides", "creixent", "estacions", "intencio", "mandat", "menjar", "nivells", "oncle", "costes", "minuts", "monument", "sobirania", "usat", "comunistes", "dotze", "etapes", "famosa", "biblioteca", "marit", "poesia", "socialistes", "augmentar", "companys", "dedicar", "escrits", "establiment", "ocupat", "pista", "sobira", "substituir", "substituit", "temperatures", "cuina", "metall", "sorgir", "joventut", "possiblement", "Romania", "taula", "Castello", "occident", "triomf", "actes", "decoracio", "democratica", "Saragossa", "augment", "coses", "documents", "estret", "Persia", "Rin", "breu", "destinat", "moderns", "sovietics", "arran", "catolic", "destruccio", "humanitat", "incloure", "laterals", "ulls", "basa", "Eduard", "entrenador", "escrita", "obert", "pacte", "parlar", "generacio", "gens", "ofensiva", "periodes", "pren", "continuacio", "corda", "deus", "electric", "et", "monarca", "nebot", "trenta", "cambra", "composta", "perdut", "planetes", "acte", "ona", "plans", "policia", "turcs", "can", "nazi", "comercials", "gel", "historicament", "Prússia", "viatjar", "cavall", "cristia", "peça", "capa", "completa", "mostrar", "quarter"]
def demana_paraula():
    paraula = getpass("Entra una paraula -> ")

    return paraula


paraula_a_encertar = random.choice(llista_paraules)
paraula_a_encertar = demana_paraula()
print(paraula_a_encertar)